### ISSUE TITLE
Logs appear during RSPEC

### ISSUE THREAD

**Issue by draffo-dc** [Wolox/wor-requests#36] opened 2017-12-29 15:19 UTC
The request logs appear during the rspec run. 
The requests are stubbed to return specific response with webmock

```
▶ rspec .

Randomized with seed 46047
[rspec-sidekiq] WARNING! Sidekiq will *NOT* process jobs in this environment. See https://github.com/philostler/rspec-sidekiq/wiki/FAQ-&-Troubleshooting
...................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................I, [2017-12-29T11:58:17.632939 #5087]  INFO -- : ATTEMPTING TO: get admin token
E, [2017-12-29T11:58:17.635055 #5087] ERROR -- : ERROR when trying to get admin token. Got status code: 500. 
.I, [2017-12-29T11:58:17.670625 #5087]  INFO -- : ATTEMPTING TO: get admin token
I, [2017-12-29T11:58:17.672560 #5087]  INFO -- : SUCCESS: get admin token
I, [2017-12-29T11:58:17.673180 #5087]  INFO -- : ATTEMPTING TO: register vehicle 556
E, [2017-12-29T11:58:17.674881 #5087] ERROR -- : ERROR when trying to register vehicle 556. Got status code: 500. 
.I, [2017-12-29T11:58:17.704330 #5087]  INFO -- : ATTEMPTING TO: get admin token
I, [2017-12-29T11:58:17.706026 #5087]  INFO -- : SUCCESS: get admin token
I, [2017-12-29T11:58:17.706157 #5087]  INFO -- : ATTEMPTING TO: register vehicle 557
I, [2017-12-29T11:58:17.707024 #5087]  INFO -- : SUCCESS: register vehicle 557
.I, [2017-12-29T11:58:17.744163 #5087]  INFO -- : ATTEMPTING TO: get admin token
I, [2017-12-29T11:58:17.745895 #5087]  INFO -- : SUCCESS: get admin token
I, [2017-12-29T11:58:17.746018 #5087]  INFO -- : ATTEMPTING TO: register vehicle 558
I, [2017-12-29T11:58:17.746900 #5087]  INFO -- : SUCCESS: register vehicle 558
.I, [2017-12-29T11:58:17.781548 #5087]  INFO -- : ATTEMPTING TO: get admin token
I, [2017-12-29T11:58:17.783540 #5087]  INFO -- : SUCCESS: get admin token
I, [2017-12-29T11:58:17.783714 #5087]  INFO -- : ATTEMPTING TO: register vehicle 559
I, [2017-12-29T11:58:17.784725 #5087]  INFO -- : SUCCESS: register vehicle 559
.I, [2017-12-29T11:58:17.822138 #5087]  INFO -- : ATTEMPTING TO: get admin token
I, [2017-12-29T11:58:17.823979 #5087]  INFO -- : SUCCESS: get admin token
I, [2017-12-29T11:58:17.824119 #5087]  INFO -- : ATTEMPTING TO: register vehicle 560
I, [2017-12-29T11:58:17.825087 #5087]  INFO -- : SUCCESS: register vehicle 560
.........................................................................................................................................................................................................................................................................................................................................................................................................................................

```

**Comment by Enanodr** [comment] 2017-12-29 17:44
I manage to bypass the problem adding this to my app
``` ruby
# config/initializers/wor_requests.rb
Wor::Requests.configure do |config|
 config.logger = Rails.logger
 if Rails.env.test?
   LoggerMock = Struct.new(nil) do
     def info(str); end
     def error(str); end
   end
   config.logger = LoggerMock.new
 end
end
```

**Comment by tagonzalez** [comment] 2019-11-28 15:55
I can't seem to reproduce the issue as is commented.
I can see logging for `wor-requests` in `test.log` file, but not in the console at the moment of running `bundle exec rspec spec -fd` like reporter states.

I have added the suggested solution and this seems to remove the logging from `test.log`, however I'm not sure if this is something we want from the gem. If that is the case, I have no problem in submitting a PR.

**Comment by blacksam07** [comment] 2019-12-02 15:57
thanks for this analysis, I close this PR because it's important to continue logging from `test.log`.

**Closed as completed by blacksam07** 2019-12-02 15:57 UTC
Labels: bug
